---
# OBS: Field in the lab is about half the real field of league B
# see: https://robocup-ssl.github.io/ssl-rules/sslrules.html#_field_setup

POINTS_PER_METER : 1000 # Conversion factor from meters to field Point coordinates # deprecating this parameter
BALL_RADIUS      : 21.5 # Approximate ball radius in millimeters.
#                                                                            #| League A || League B ||   LAB    |
#                                                                            #|==================================|                  
FIELD_LENGTH     : 9000 # The goal-to-goal-line length                       #|  12000   ||   9000   ||   4500   |                                      
FIELD_WIDTH      : 6000 # The side-to-side length                            #|   9000   ||   6000   ||   3000   |                                          
CENTER_RADIUS    :  500 # Radius of the circle in the center of the field    #|    500   ||    500   ||    500   |
#                                                                            #|----------||----------||----------|
DEF_AREA_LENGTH  : 2000 # Length of the defence area (distance y direction)  #|   3600   ||   2000   ||   1000   |
DEF_AREA_WIDTH   : 1000 # Width  of the defence area (distance x direction)  #|   1800   ||   1000   ||    500   |
GOAL_LENGTH      : 1000 # Length of the goal post (distance y direction)     #|   1800   ||   1000   ||    500   |
PENALTY_MARK     : 3000 # distance from goal at which penalties are taken    #|   8000   ||   6000   ||   3000   |

#
#
#    NOTE: Coordinate (0,0) is at the center of the field
#     y axis
#     ^                                            HALF_FIELD_LENGTH
#     |                                         <---------------------->       
#     --->              -----------------------------------------------           
#    x axis            |                       |  ^                    |    
#                 ^    |-----                  |  | HALF          -----|    
#                 |    |     |                 |  | FIELD        |     |        
#                 |   -|     |                 |  | WIDTH        |     |-  
#            DEF  |  | |     |                o|o v              |     | |  ^  DEF
#          LENGTH |  | |-----|--------------o--|--o--------------|-----| |  |  AREA     
#           AREA  |  | |     |                o|o                |     | |  V LENGTH
#                 |   -|     |                 |                 |     |-          
#                 |    |     |                 |                 |     |             
#                 V    |-----                  |                  -----|
#                      |                       |                       |
#                       -----------------------------------------------
#                       <--->                  |->
#                   DEF_AREA_WIDTH       CENTER_RADIUS
#               




