---
TEAM_BLUE :
    SIDE: 1 # 0  negative side, 1 positive side
    # Define the roles of each robot



    # ROBOT_PROXY
      # TYPE: yisibot           # alternatives: grsim yisibot rpi_2019 none
      # USB_PORT : /dev/ttyUSB1 # yisi usb port
      # FREQUENCY: 0            # radio frequency channel at which robots are communicating 
    
    # if robot type == grsim, then must specify:
    ROBOT_PROXY:
      TYPE : grsim # alternatives: grsim yisibot rpi_2019 none
      ADDR : 127.0.0.1 # ip of grsim
      PORT : 20011     # port of grsim
      
    STRATEGY_CONTROLLER:
      # ID: STRATEGY_TESTER # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK or none
      # define your own 'key : value' pairs to load on your test strategies
      
      # ID : JOYSTICK        # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK
      # JOY_TO_ROBOT_MAP :
      #   - ROBOT : 0
      #     JOY   : 0
      #  - ROBOT : 1
      #    JOY   : 1
      
       ID: NORMAL_GAME # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK
       ROLES:
         GOALIE : 5
         ATTACK1 : 3
         ATTACK2 : 0
         ATTACK3 : 1
         ATTACK4 : 2
         DEFEND1 : 4
         DEFEND2 : 6
         DEFEND3 : 7
    
    # support for rpi_2019 is work in progress
    
TEAM_YELLOW :
    SIDE: 0
    
    ROBOT_PROXY: 
      TYPE : none 
    
    STRATEGY_CONTROLLER:
      ID: none
    
    
    
    
