---
TEAM_BLUE :
    SIDE: 0 # 0  negative side, 1 positive side
    # Define the roles of each robot

    ROBOT_PROXY:
        TYPE : grsim # alternatives: grsim yisibot rpi_2019 none
        ADDR : 127.0.0.1 # ip of grsim
        PORT : 20011     # port of grsim

    # ROBOT_PROXY
    #   TYPE: grsim          # alternatives: grsim yisibot rpi_2019 none
      # USB_PORT : /dev/ttyUSB1 # yisi usb port
      # FREQUENCY: 0            # radio frequency channel at which robots are communicating 
    
    # if robot type == grsim, then must specify:


    #ROBOT_PROXY:
     # TYPE : rpi_2019 # alternatives: grsim yisibot rpi_2019 none
        ROBOT:
            1:
                ADDR: 127.0.0.1
                PORT: 20012
            2:
                ADDR: 127.0.0.1
                PORT: 20014
     # ADDR : 127.0.0.1 # ip of grsim
     # PORT : 20011     # port of grsim

      #TYPE: yisibot
        USB_PORT: \\.\COM3
        FREQUENCY: 0
      
    STRATEGY_CONTROLLER:
      # ID: STRATEGY_TESTER # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK or none
      # define your own 'key : value' pairs to load on your test strategies
      
      # ID : JOYSTICK        # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK
      # JOY_TO_ROBOT_MAP :
      #   - ROBOT : 0
      #     JOY   : 0
      #  - ROBOT : 1
      #    JOY   : 1
      
        ID: NORMAL_GAME # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK
        ROLES:
            GOALIE : 0
            ATTACK1 : 1
            ATTACK2 : 2
            #ATTACK3 : 3
            #ATTACK4 : 6
            #DEFEND1 : 4
            #DEFEND2 : 5
            #DEFEND3 : 7
    
    # support for rpi_2019 is work in progress
    
TEAM_YELLOW :
    SIDE: 1
    
    ROBOT_PROXY:
        TYPE : grsim # alternatives: grsim yisibot rpi_2019 none
        ADDR : 127.0.0.1 # ip of grsim
        PORT : 20011     # port of grsim
    
    STRATEGY_CONTROLLER:
        ID: NORMAL_GAME # options: NORMAL_GAME or STRATEGY_TESTER or JOYSTICK
        ROLES:
            GOALIE : 0
            ATTACK1 : 1
            ATTACK2 : 2
            #ATTACK3 : 3
            #ATTACK4 : 2
            #DEFEND1 : 4
            #DEFEND2 : 5
            #DEFEND3 : 7
    
    
    
    
