---
VISION_ADDR : 224.5.23.2 # vision: 224.5.23.2,  simulation: 127.0.0.1
VISION_PORT : 10006      # vision: 10006,       simulation: 20011
FOUR_CAMERA : false

REFBOX_ADDR : 224.5.23.1
REFBOX_PORT : 10001
REFBOX_ENABLED : true







